In [167]:
from abc import ABC
import numpy as np

A = np.array([[0,1],[2,3],[4,5]])
B = np.array([[0,1,2,3],[4,5,6,7]])

print(A)
print(B)

[[0 1]
 [2 3]
 [4 5]]
[[0 1 2 3]
 [4 5 6 7]]


In [168]:
np.dot(A,B)

array([[ 4,  5,  6,  7],
       [12, 17, 22, 27],
       [20, 29, 38, 47]])

In [169]:
print(np.dot(A,B))

[[ 4  5  6  7]
 [12 17 22 27]
 [20 29 38 47]]


In [170]:
np.dot(A,B).max()

47